<?php
$headTitle = 'Add article';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-xs-6">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
    <div class="col-xs-6">
        <div class="breadcrumb-box">
            <?= $this->navigation('navigation')->breadcrumbs()->setminDepth(1)->setPartial('partial/breadcrumb') ?>
        </div>
    </div>
</div>
<br>
<h4>Form for adding article:</h4>
<br>
<div class="row">
    <div class="col-lg-8 col-md-10">
        <div class="well">
        <?php
            $this->form->setAttribute('action', $this->url('admin/article', ['action' => 'add']));
            $this->form->prepare();

        echo $this->form()->openTag($this->form);

        foreach ($this->form as $element) {
            $attributes = $element->getAttributes();
            $label = '';
            $formElement = '';

            echo "<div class='form-group'>";
                if ($element->getLabel()) {
                    $element->setLabelAttributes([
                        'class' => 'control-label',
                    ]);

                    if (isset($attributes['required']) && $attributes['required'] == 'required') {
                        $element->setLabel($element->getLabel() . ' *');
                    }

                    $label = $this->formLabel($element);
                    $label = str_replace('*', '<strong class="star-required">*</strong>', $label);
                }

                switch ($attributes['type']) {
                    case 'text':
                        $formElement = $this->formText($element);
                    break;
                    case 'textarea':
                        $formElement = $this->formTextarea($element);
                    break;
                    case 'select':
                        $formElement = $this->formSelect($element);
                    break;
                    case 'checkbox':
                        $formElement = $this->formCheckbox($element);
                    break;
                    case 'submit':
                        $formElement = $this->formSubmit($element);
                    break;
                }

                echo "<div class='col-md-2'>" . $label . "</div>" .
                     "<div class='col-md-10'>" . $formElement . $this->formElementErrors($element) . "</div>";
            echo "</div>";
        }

        echo $this->form()->closeTag();
        ?>
        </div>
    </div>
</div>
