<?php
$headTitle = 'Articles';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-xs-6">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
    <div class="col-xs-6">
        <div class="breadcrumb-box">
            <?= $this->navigation('navigation')->breadcrumbs()->setminDepth(1)->setPartial('partial/breadcrumb') ?>
        </div>
    </div>
</div>
<br>
<div><a href="<?= $this->url('admin/article', ['action' => 'add']) ?>" class="btn btn-default">Add article</a></div>
<br>
<div class="row">
    <div class="col-lg-3 col-md-4">
        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s>
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
             <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        ?>
    </div>
</div>
<br>
<?php if (! $this->articles) : ?>
<h5>List is empty</h5>
<?php else : ?>
<div class="table-responsive">
    <table class="table table-hover table-striped">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Short Article</th>
            <th>Article</th>
            <th>Category</th>
            <th>Is public</th>
            <th>Actions</th>
        </tr>
        <?php foreach ($this->articles as $article) : ?>
        <tr>
            <td><?= ($this->currentPageNumber - 1) * $itemCountPerPage + ++$this->i ?></td>
            <td><?= $this->escapeHtml($article->getTitle()) ?></td>
            <td>
                <span data-toggle="tooltip" data-placement="top" title="<?= $this->escapeHtml($article->getShortArticle()) ?>">
                    <?= mb_substr($this->escapeHtml($article->getShortArticle()), 0, 10) . '....' ?>
                </span>
            </td>
            <td>
                <span data-toggle="tooltip" data-placement="top" title="<?= $this->escapeHtml($article->getArticle()) ?>">
                    <?= mb_substr($this->escapeHtml($article->getArticle()), 0, 10) . '....' ?>
                </span>
            </td>
            <td><?= $this->escapeHtml($article->getCategory()->getCategoryName()) ?></td>
            <td><?= $this->escapeHtml($article->getIsPublic()) ? 'Yes' : 'No'; ?></td>
            <td>
                 <a href="<?= $this->url('admin/article', ['action' => 'edit', 'id' => (int)$article->getId()]) ?>">
                     Edit
                 </a>
                 &nbsp;&nbsp;|&nbsp;&nbsp;
                 <a href="<?= $this->url('admin/article', ['action' => 'delete', 'id' => (int)$article->getId()]) ?>"
                    onclick="return confirm('Are You sure?')"
                 >
                     Delete
                 </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<?php endif; ?>
<br>
<br>
<?php
echo $this->paginationControl(
    $this->articles,
    'sliding',
    'partial/paginator.phtml',
    ['route' => 'admin/article']
);
?>
