<?php
$headTitle = 'Add category';
$this->headTitle($headTitle);
$breadcrumb = $this->navigation('navigation')->breadcrumbs()->setminDepth(1)->setPartial('partial/breadcrumb');
?>
<?= $this->displayTitleAndBreadcrumb($headTitle, $breadcrumb) ?>
<br>
<br>
<div class="well">
<?php
$this->form->setAttribute('action', $this->url('admin/category', ['action' => 'add']));
$this->form->prepare();

echo $this->form()->openTag($this->form);

echo "<fieldset><legend>Form for adding category</legend>";

foreach ($this->form as $element) {
    $attributes = $element->getAttributes();
    $label = '';
    $formElement = '';

    echo "<div class='form-group'>";

        if ($element->getLabel()) {
            $element->setLabelAttributes([
                'class' => 'control-label',
            ]);

            if (isset($attributes['required']) && $attributes['required'] = 'required') {
                $element->setLabel($element->getLabel() . ' *');
            }

            $label = $this->formLabel($element);
            $label = str_replace('*', '<strong class="star-required">*</strong>', $label);
        }

        switch ($attributes['type']) {
            case 'text':
                $formElement = $this->formText($element);
            break;
            case 'submit':
                $formElement = $this->formSubmit($element);
            break;
        }

        echo "<div class='col-md-2'>" . $label . "</div>" .
             "<div class='col-md-10'>" . $formElement . $this->formElementErrors($element) . "</div>";

    echo "</div>";
}

echo "</filedset>";

echo $this->form()->closeTag();
?>
</div>
