<?php
$headTitle = $this->article->getTitle();
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-xs-6">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
    <div class="col-xs-6">
        <div class="breadcrumb-box">
            <?= $this->navigation('navigation')->breadcrumbs()->setminDepth(1)->setPartial('partial/breadcrumb') ?>
        </div>
    </div>
</div>
<br>
<section>
    <div><?= $this->article->getArticle() ?></div>
</section>
<br>
<div><a href="/blog">&lArr; Back</a></div>
<br>
<br>
<button class="btn btn-primary" 
        type="button" 
        data-toggle="collapse" 
        data-target="#collapseExample" 
        aria-expanded="false" 
        aria-controls="collapseExample"
>Open for comment</button>
<div class="collapse" id="collapseExample">
    <br>
    <div class="well">
        <?php
        $this->form->setAttributes([
            'action' => $this->url('blog', ['action' => 'add-comment']),
            'class'  => 'form-horizontal',
        ]);
        $this->form->prepare();

        echo $this->form()->openTag($this->form);
            echo "<fieldset><legend>Add comment</legend><br>";

            foreach ($this->form as $element) {
                $formElement = '';
                $label = '';
                $attributes = $element->getAttributes();

                if ($element->getLabel()) {
                    $element->setLabelAttributes([
                        'class' => 'control-label col-lg-2'
                    ]);

                    if (isset($attributes['required']) && $attributes['required'] == 'required') {
                        $element->setLabel($element->getLabel() . ' *');
                    }

                    $label = $this->formLabel($element);
                    $label = str_replace("*", "<strong class='star-required'>*</strong>", $label);
                }

                switch ($attributes['type']) {
                    case 'hidden':
                        $formElement = $this->formHidden($element);
                    break;
                    case 'email':
                        $formElement  = '<div class="col-lg-10">';
                        $formElement .= $this->formEmail($element);
                        $formElement .= '</div>';
                    break;
                    case 'textarea':
                        $formElement  = '<div class="col-lg-10">';
                        $formElement .= $this->formTextarea($element);
                        $formElement .= '</div>';
                    break;
                    case 'submit':
                        $formElement  = '<div class="col-lg-12 col-lg-offset-2">';
                        $formElement .= $this->formSubmit($element);
                        $formElement .= '</div>';
                    break;
                }

                echo '<div class="form-group">' . $label . $formElement . '</div>';
            }

            echo "</fieldset>";
        echo $this->form()->closeTag();
        ?>
    </div>  
</div>
